CREATE TABLE study (
    study_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    study_matter VARCHAR(255) NOT NULL,

    CONSTRAINT pk_study PRIMARY KEY (study_id)
);

CREATE TABLE topic (
    topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    topic_title VARCHAR(255) NOT NULL,
    study_id BIGINT,
    topic_parent_id BIGINT,

    CONSTRAINT pk_topic PRIMARY KEY (topic_id),
    CONSTRAINT fk_topic_study FOREIGN KEY (study_id) REFERENCES study(study_id),
    CONSTRAINT fk_topic_parent FOREIGN KEY (topic_parent_id) REFERENCES topic(topic_id)
);

CREATE TABLE document (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_title VARCHAR(255) NOT NULL,
    document_content TEXT,
    study_id BIGINT,
    topic_id BIGINT,

    CONSTRAINT pk_document PRIMARY KEY (document_id),
    CONSTRAINT fk_document_study FOREIGN KEY (study_id) REFERENCES study(study_id),
    CONSTRAINT fk_document_topic FOREIGN KEY (topic_id) REFERENCES topic(topic_id)
);


